name: asocapp
description: 'A new Flutter project.'
publish_to: 'none'
version: 0.1.0

environment:
    sdk: ^3.6.0-216.1.beta

dependencies:
    device_info_plus: ^11.1.1
    easy_localization: ^3.0.7
    equatable: ^2.0.7
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.6
    flutter_localizations:
        sdk: flutter
    fpdart: ^1.1.1
    get_it: ^8.0.2
    go_router: ^14.6.2
    hive: ^4.0.0-dev.2
    intl: ^0.19.0
    local_auth: ^2.3.0
    package_info_plus: ^8.1.2
    path_provider: ^2.1.5

dev_dependencies:
    flutter_lints: ^5.0.0
    flutter_test:
        sdk: flutter

flutter:
    uses-material-design: true

    # To add assets to your application, add an assets section, like this:
    assets:
        - assets/images/
        - assets/fonts/
        - assets/translations/
flutter_intl:
    enabled: true
